apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.23.0
    helm:
      parameters:
        - name: server.affinity
          value: ""
        - name: server.ha.enabled
          value: "true"
        - name: server.ha.raft.enabled
          value: "true"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: vault
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
