kube-prometheus-stack:
  prometheus-node-exporter:
    hostRootFsMount: false
  nodeExporter:
    enabled: true
  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.localhost
