kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      hosts:
        - host: grafana.localhost
          paths:
            - path: /
              pathType: ImplementationSpecific
          tls: []
