linkerd-control-plane:
  proxyInit:
    privileged: true
    runAsRoot: true
  identityTrustAnchorsPEM: |-
    -----BEGIN CERTIFICATE----- MIIBjTCCATOgAwIBAgIQTEO1MZJcOY5a6dO0QUOVYDAKBggqhkjOPQQDAjAlMSMw IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMzAxMDkyMTQ0 MzdaFw0yODAxMDgyMTQ0MzdaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEW/CmYFaSdBHRwftY k0d94zrvAtCx1xaBAuRMR0ZBmhbSAgBVsmXBzNTqsfQr8BTorwj2myR1xLn40IxJ JWqvRaNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD VR0OBBYEFN/LpHcvSZjf4UjSGVHPzpZ4Zm1JMAoGCCqGSM49BAMCA0gAMEUCICYv GldRgr6ig+EYZiXKcHcU2yd7xssjr9zWX0fLaNT+AiEAgYsZJ1pj2v5fzlas+GzW 5CoCZSfXkLhYU1VqcOh17to= -----END CERTIFICATE-----
  identity:
    issuer:
      scheme: kubernetes.io/tls
