linkerd-control-plane:
  proxyInit:
    privileged: true
    runAsRoot: true
  identityTrustAnchorsPEM: |
    -----BEGIN CERTIFICATE-----
    MIIBjjCCATSgAwIBAgIRAPae/d5WYiP1gfYysWNXlCIwCgYIKoZIzj0EAwIwJTEj
    MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjMwMTA5MjEy
    ODA2WhcNMjgwMTA4MjEyODA2WjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
    c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABLdA1nJYDyz1h4J0
    +hc3ThiJOXsE56xkCuWWMu6HRyvxm7oyfbVLQuCtNgxFltIrInocRv+E6VyFw7JI
    zOykezijRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
    A1UdDgQWBBTVVbfpU5sjzknd4Dc6xKuG/B4m/TAKBggqhkjOPQQDAgNIADBFAiEA
    yXEl4KOf8syVSbG/wLglEh+CSOMQOtxQjBegSb3Y004CIHtpbWqhnKy5PrTXMSLj
    +3Pd2LvHg+dKef+stg4+gpdj
    -----END CERTIFICATE-----
  identity:
    issuer:
      scheme: kubernetes.io/tls
