linkerd-control-plane:
  proxyInit:
    privileged: true
    runAsRoot: true
  identityTrustAnchorsPEM: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  identity:
    issuer:
      scheme: kubernetes.io/tls
