linkerd-control-plane:
  proxyInit:
    privileged: true
    runAsRoot: true
  identityTrustAnchorsPEM: |-
    -----BEGIN CERTIFICATE----- MIIBjjCCATOgAwIBAgIQUmZTwZRIVOTrLRWO0iK4pzAKBggqhkjOPQQDAjAlMSMw IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMzAxMDgyMDAx MjZaFw0yODAxMDcyMDAxMjZaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEXqsIJn4lmQKBR5os zzmy7kxQIVAC/lEozDQE1VgT8oad9dmEKGCJUrKUpCTXNmu1HMVAqaNuTbpZk4MO k4adhqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD VR0OBBYEFOHgYfl2uug3HpRURKZS9YRWQ2grMAoGCCqGSM49BAMCA0kAMEYCIQCB tCMxUH/r5KQTqGLPw+8+DRAfscQkkD8H2zufo5RdcQIhAJwAooLQmWukdrhcYcnK c1w6cLd5iBqonY/nXC2xn84Q -----END CERTIFICATE-----
  identity:
    issuer:
      scheme: kubernetes.io/tls
