linkerd-control-plane:
  proxyInit:
    privileged: true
    runAsRoot: true
  identityTrustAnchorsPEM: |
    -----BEGIN CERTIFICATE-----
    MIIBjTCCATOgAwIBAgIQDJRAxDv65ka0WC951JW2EzAKBggqhkjOPQQDAjAlMSMw
    IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMzAxMDYyMDA2
    MjRaFw0yODAxMDUyMDA2MjRaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
    dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEX4ZqesFQ9k1lgfF2
    bF2TfGNHzYqih9Z0vJrgwRzQAULptNInRsexSK/JjHsWrJduDAkTiiBMM/CfuREH
    gxAXG6NFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
    VR0OBBYEFJLkZcevl/g+6U8Bf73EpKeIFoiwMAoGCCqGSM49BAMCA0gAMEUCIDUs
    szq2ahk7pYxrLz/ORdJsbEtXCtSzbEyGpFTzFRThAiEA3Oh47z1Qrs134Y6GXFI7
    Iqn+lAJ1GqlCnIQxgU9v6HM=
    -----END CERTIFICATE-----
  identity:
    issuer:
      scheme: kubernetes.io/tls
