linkerd-control-plane:
  proxyInit:
    privileged: true
    runAsRoot: true
  identityTrustAnchorsPEM: |-
    -----BEGIN CERTIFICATE-----
    MIIBjjCCATSgAwIBAgIRAKptV98OaiFW14yGns2nFvYwCgYIKoZIzj0EAwIwJTEj
    MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjMwMTEwMTMz
    NDI0WhcNMjgwMTA5MTMzNDI0WjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
    c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABISVvre+czkfvrY2
    BwKeIQxr3BjMso1eSv5QhVDQHaYmoc/mkIaoE/zck+ed/cHV+g3HNG/iwHMpMrC7
    HiTdjKGjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
    A1UdDgQWBBQWUSYDt08gnBkwUeuQBSDMAlofhTAKBggqhkjOPQQDAgNIADBFAiAY
    EJMeT+euAp5BnKhjRhBOLVDug3sSqcKF2WCObWZmPAIhANfDN1qf6kXzEpD/HWSe
    65/HOi9vJwC3/zDFv0VYflYs
    -----END CERTIFICATE-----
  identity:
    issuer:
      scheme: kubernetes.io/tls
