linkerd-control-plane:
  proxyInit:
    privileged: true
    runAsRoot: true
  identityTrustAnchorsPEM: |-
    -----BEGIN CERTIFICATE-----
    MIIBjTCCATOgAwIBAgIQMpfC195QYeG1HuNR1v4zajAKBggqhkjOPQQDAjAlMSMw
    IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMzAxMTAxNDIy
    NTlaFw0yODAxMDkxNDIyNTlaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
    dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEHtiuJVUFeLjjadx7
    3+R5yY/ag55mJzwh2nncVjhoa6gTDK7kWnz41JR+OronuNCpVLSEMlX63jh0NxQx
    dOEbgqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
    VR0OBBYEFNic3pO4rYc4ll6ELybjCzRQPwBCMAoGCCqGSM49BAMCA0gAMEUCIQDw
    /3RVhB2chrasyDiWiIuIc2Dz7N/52EsEQ+eD7fPTMQIgfG5vG3EaofzfZjrkaKSo
    X/kE+ZedXjyXPRlavMuMS64=
    -----END CERTIFICATE-----
  identity:
    issuer:
      scheme: kubernetes.io/tls
