---
## ArgoCD configuration
## Ref: https://github.com/argoproj/argo-cd
##
## Server
argo-cd:
  server:
    ## ArgoCD config
    ## reference https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
    configEnabled: true
    config:
      repositories: |
        - type: git
          url: https://github.com/wevanscfi/homelab.git
        - name: argo-helm
          type: helm
          url: https://argoproj.github.io/argo-helm
    additionalApplications:
      - name: argocd
        namespace: argocd
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: argocd
        source:
          helm:
            version: v3
            valueFiles:
            - values.yaml
          path: charts/argocd
          repoURL: https://github.com/wevanscfi/homelab.git
          targetRevision: HEAD
        syncPolicy:
          syncOptions:
          - CreateNamespace=true
      - name: argocd-apps
        namespace: argocd
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: argocd
        source:
          path: manifests/apps
          repoURL: https://github.com/wevanscfi/homelab.git
          targetRevision: HEAD
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
      - name: cluster
        namespace: argocd
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: argocd
        source:
          path: manifests/cluster
          repoURL: https://github.com/wevanscfi/homelab.git
          targetRevision: HEAD
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
    additionalProjects:
    - name: argocd
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      description: Argocd Project
      sourceRepos:
      - '*'
      destinations:
      - namespace: argocd
        server: https://kubernetes.default.svc
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      orphanedResources:
        warn: false
